var a = 33;
var b = 10;
var c = "Test";
var result;
result = a + b;
console.log(result);
result = a - b;
console.log(result);
result = a / b;
console.log(result);
result = a % b;
console.log(result);
result = a + b + c;
console.log(result);
a = a++;
result = a++;
console.log(result);
b = b--;
result = b--;
console.log(result);