var a = 2;
var b = 3;
var result;
result = a & b;
console.log(result);
result = a | b;
console.log(result);
result = a ^ b;
console.log(result);
result = ~b;
console.log(result);
result = a << b;
console.log(result);
result = a >> b;
console.log(result);
result = a >>> b;
console.log(result);