var a = 33;
var b = 10;
var c = "Test";
var result;
result = a = b;
console.log(result);
result = a += b;
console.log(result);
result = a -= b;
console.log(result);
result = a *= b;
console.log(result);
result = a /= b;
console.log(result);
result = a %= b;
console.log(result);
result = a >>= b;
console.log(result);