var a = 10;
var b = "String";
var c = "number";
var d = "boolean";
var e = "object";
var f = "function";
var g = "undefined";
result = (typeof b == "string" ? "B is String" : "B is Numeric");
console.log(result);
result = (typeof a == "string" ? "A is String" : "A is Numeric");
console.log(result);
result = (typeof d == "boolean" ? "B is String" : "B is object");
console.log(result);
result = (typeof e == "object" ? "A is String" : "A is Numeric");
console.log(result);
result = (typeof f == "function" ? "B is String" : "B is Numeric");
console.log(result);
result = (typeof g == "undefine" ? "A is String" : "A is Numeric");
console.log(result);
result = (typeof c == "string" ? "A is String" : "A is Numeric");
console.log(result);